### ISSUE TITLE
Dismiss button on flash message will submit forms

### ISSUE THREAD

**Issue by 5ero** [mattlibera/livewire-flash#13]
When used inside a form with  wire:submit.prevent, I clicked on the cross to dismiss the flash message but instead it attempts to resubmit the form.

The flash message close button attempts to submit the form. 
flash('<message>')->success()->livewire($this)

This does not happen when using overlay.
flash()->overlay('<message>', '<title>')->livewire($this);

**Comment by mattlibera** [comment]
Hi @5ero - thanks for using the package.

This should only ever be an issue if the `<livewire:flash-container>` element is placed inside a `<form>` element. That's not something I've ever really done myself, so I didn't think about this too hard when writing the view. The quick fix should be to move that element outside your form.

But, I do think an actual fix would be quite simple. The "dismiss" button on the flash message is a `<button>' element, and the default behavior of a `<button>` element inside a form is to submit the form, unless told otherwise. We should be able to prevent this simply by adding the `type="button"` attribute to the `<button>` inside the flash message view.

I will try and test this out sometime in the next few days, but if you are able to try this on your own and confirm that it works, let me know.

**Comment by 5ero** [comment]
Hi,
Thanks for the quick reply, I’ll take a look and let you know

**Comment by mattlibera** [comment]
Hi @5ero , just going through some issues and wondering if you've been able to test the solution suggested above. If not, I will try this week and maybe push an update if it works.

Thanks!
